const QueryKeys = {
  DRIVERS_STANDINGS: 'DRIVERS_STANDINGS',
  CONSTRUCTORS_STANDINGS: 'CONSTRUCTORS_STANDINGS',
  RACES: 'RACES',
  DRIVERS_RESULTS: 'DRIVERS_RESULTS',
};

export default QueryKeys;
